### ISSUE TITLE
How to setDecorators On Specific date

### ISSUE THREAD

**Issue by kamalupasena** [npanigrahy/Custom-Calendar-View#1]
Can you give us a example on how to set decorator on specific date ?

**Comment by npanigrahy** [comment]
Example already available in sample application. 

Declare a custom decorator by implementing DayDecorator interface.

```java
private class ColorDecorator implements DayDecorator {

        @Override
        public void decorate(DayView cell) {
            Random rnd = new Random();
            int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
            cell.setBackgroundColor(color);
        }
    }
```

Now, set the custom decorator using,
```java
Calendar currentCalendar = Calendar.getInstance(Locale.getDefault());
calendarView = (CustomCalendarView) view.findViewById(R.id.custom_calendar_view);

final ArrayList<ColorDecorator> decorators = new ArrayList<>();
decorators.add(new ColorDecorator());
calendarView.setDecorators(decorators);
```

**Comment by kamalupasena** [comment]
Thank you very much

**Comment by kamalupasena** [comment]
I have created a Class Implementing the DayDecorator

```public class EventDecore implements DayDecorator {```

    private Date eventDate;

    public EventDecore(Date eventDate) {
        this.eventDate = eventDate;
    }

    @Override
    public void decorate(DayView dayView) {
        if (dayView.getDate() == eventDate) {
            Random rnd = new Random();
            int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
            dayView.setBackgroundColor(color);
        }
    }

}

and  i have added like this 

```final ArrayList<EventDecore> decorators = new ArrayList<>();
decorators.add(new EventDecore(Calendar.getInstance().getTime()));
calendarView.setDecorators(decorators);```


now i am getting a error saying like this 

```method setDecorators in class CustomCalendarView cannot be applied to given types;
required: List<DayDecorator>
found: ArrayList<EventDecore>
reason: actual argument ArrayList<EventDecore> cannot be converted to List<DayDecorator> by method invocation conversion```

How can i fixed this ?

**Comment by kamalupasena** [comment]
Just Minor thing 
`final ArrayList<ColorDecorator> decorators = new ArrayList<>();`
should be change to 
`final ArrayList< DayDecorator> decorators = new ArrayList<>();`

**Comment by jorgecasariego** [comment]
Thanks @npanigrahy
