### ISSUE TITLE
Disable all previous dates from current date and disable unavailable dates

### ISSUE THREAD

**Issue by AmeyJahagirdar1991** [npanigrahy/Custom-Calendar-View#11]
If a user wants to book an appointment, all the previous dates from current date should be disabled and it should also disable weekend dates as well as unavailable dates

**Comment by StackTipsLab** [comment]
You need to use the DaysDecorator to achieve this. Here is the sample code that might help you.
http://stacktips.com/tutorials/android/custom-calendar-view-library-in-android

```
private class DaysDecorator implements DayDecorator {
    @Override
    public void decorate(DayView dayView) {
        if(!isPastDay(dayView.getDate())){
            dayView.setBackgroundColor(getResources().getColor(R.color.disable_color));
        }
    }
}
private boolean isPastDay(Date date) {
    Calendar c = Calendar.getInstance();

    // set the calendar to start of today
    c.set(Calendar.HOUR_OF_DAY, 0);
    c.set(Calendar.MINUTE, 0);
    c.set(Calendar.SECOND, 0);
    c.set(Calendar.MILLISECOND, 0);

    // and get that as a Date
    Date today = c.getTime();

    // test your condition, if Date specified is before today
    if (date.before(today)) {
        return true;
    }
    return false;
}
```

**Comment by darshanpopat** [comment]
Hello,

Thanks for the awesome library for CalendarView.
One thing I want to do it, I want to make all past date Unselectable in Calendar.
No past date should be selected. And no one should go to past month as well.
Can you help me achieve this ?

Thanks In Advance.

**Comment by npanigrahy** [comment]
Check this.
http://stacktips.com/tutorials/android/disable-past-dates-in-custom-calendar-view-android
