### ISSUE TITLE
Getting Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0. error

### ISSUE THREAD

**Issue by sandroiddeveloper** [npanigrahy/Custom-Calendar-View#20]
Hi @npanigrahy

I need some help for integrating library.
I'm getting following error while compiling android project:
Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0.

Following is detailed files:

Top-level build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
project build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion '24.0.1'

    defaultConfig {
        applicationId "com.test.test"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.github.npanigrahy:Custom-Calendar-View:v1.0'

    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:cardview-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.+'
}
```

stack trace
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0.
     Required by:
         STYYLE:app:unspecified
      > Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0.
         > Could not get resource 'https://jcenter.bintray.com/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
               > RSA premaster secret error
      > Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0.
         > Could not get resource 'https://repo1.maven.org/maven2/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
               > RSA premaster secret error
      > Could not resolve com.github.npanigrahy:Custom-Calendar-View:v1.0.
         > Could not get resource 'https://jitpack.io/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/npanigrahy/Custom-Calendar-View/v1.0/Custom-Calendar-View-v1.0.pom'.
               > RSA premaster secret error

Thanks in advance.

**Comment by yuricavalcantedev** [comment]
Me too. is it works with you?

**Comment by sandroiddeveloper** [comment]
The issue was JDK i was using. After shifting to embedded SDK in android studio issue was resolved.

**Comment by npanigrahy** [comment]
not an issue.

**Comment by bilalparekh** [comment]
Hi, 
I want to add Event bullets on the date , how could I ?
