### ISSUE TITLE
Change Arrow Indicator Image

### ISSUE THREAD

**Issue by Kishou** [npanigrahy/Custom-Calendar-View#21]
Hi, your library is awesome.
but is it possible to change the Arrow Indicator Image for next and prev changing month in calendar view ?
I need to custom that for my assignment.
Really appreciate your help.

**Comment by bandung88** [comment]
you can get the ImageView from your calendar, then change the image resource
((ImageView) calendarView.findViewById(R.id.leftButton)).setImageResource(R.drawable.your_image);

**Comment by yash59** [comment]
is there any solution? I just wanna change arrow color to black.
