### ISSUE TITLE
Make all Past date Unselectable.

### ISSUE THREAD

**Issue by darshanpopat** [npanigrahy/Custom-Calendar-View#23]
Hello,

Thanks for the awesome library for **CalendarView**.
One thing I want to do it, I want to make all past date **Unselectable** in Calendar.
**No past date should be selected**. And no one should go to **past month** as well.
Can you help me achieve this ?

Thanks In Advance.

**Comment by npanigrahy** [comment]
See this tutorial 
http://stacktips.com/tutorials/android/disable-past-dates-in-custom-calendar-view-android
