### ISSUE TITLE
Swipe to change the month

### ISSUE THREAD

**Issue by fukhaos** [npanigrahy/Custom-Calendar-View#4]
It's possible to use the SWIPE to change the months ?

**Comment by npanigrahy** [comment]
Not supported yet.

On Thursday, 14 January 2016, Vinicius Oliveira <notifications@github.com>
wrote:

> It's possible to use the SWIPE to change the months ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npanigrahy/Custom-Calendar-View/issues/4>.
>


-- 

--

Nilanchala Panigrahy

Blogger, author and developer, London

Mobile: +44-7405 555361, +91-973 1563021

Website <http://javatechig.com> | Facebook
<https://www.facebook.com/nilanchalapanigrahy> | Linkedin
<https://uk.linkedin.com/in/npanigrahy> | Twitter
<https://twitter.com/npanigrahy> | Google+
<https://plus.google.com/u/0/+NilanchalaPanigrahy>

**Comment by shaunty21** [comment]
Is there any solution to swipable month in your app?
