### ISSUE TITLE
After day selection, the decorator disappears

### ISSUE THREAD

**Issue by FlorentUguet** [npanigrahy/Custom-Calendar-View#7]
After setting DayDecorators on a CustomCalendar, then selecting a day where the decorator was applied, the Decorator disappears.

The day that got selected, then unselected, just gets the normal look for days, and the decorator isn't reloaded.

Is there a special manipulation to do ?

**Comment by HectorFGarcia** [comment]
+1

**Comment by HectorFGarcia** [comment]
After check the code, is only one line missing.

`CustomCalendarView.java `-> line 288 -> add in line 289 `dayView.decorate();`

And the bug is gone.

**Comment by npanigrahy** [comment]
Closed.

**Comment by jorgecasariego** [comment]
@npanigrahy It is possible to see this change if I using Gradle? Because I still have this problem using gradle
